export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_START = 'SETUP_USER_START';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_CHANGE_DATE = 'HANDLE_CHANGE_DATE';
export const CLEAR_INPUTS = 'CLEAR_INPUTS';

export const CREATE_TRANSACTION_BEGIN = 'CREATE_TRANSACTION_BEGIN';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_ERROR = 'CREATE_TRANSACTION_ERROR';

export const GET_TRANSACTION_BEGIN = 'GET_TRANSACTION_BEGIN';
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';

export const SET_EDIT_TRANSACTION = 'SET_EDIT_TRANSACTION';

export const SET_DELETE_TRANSACTION = 'SET_DELETE_TRANSACTION';

export const EDIT_TRANSACTION_BEGIN = 'EDIT_TRANSACTION_BEGIN';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_ERROR = 'EDIT_TRANSACTION_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';
